---
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/internal-hostname: "clickhouse.{{ .nuon.install_stack.outputs.region }}"
    external-dns.alpha.kubernetes.io/ttl: "60"
  name: clickhouse
  namespace: clickhouse
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 8123
      protocol: TCP
      targetPort: 8123
    - name: client
      port: 9000
      protocol: TCP
      targetPort: 9000
  sessionAffinity: None
  type: ClusterIP
  selector:
    clickhouse.altinity.com/app: chop
    clickhouse.altinity.com/chi: clickhouse-installation
    clickhouse.altinity.com/namespace: clickhouse
    clickhouse.altinity.com/ready: "yes"
