[[group]]
name         = "dns"
description  = "DNS Configurations"
display_name = "DNS"

[[input]]
name         = "domain"
description  = "Root domain for DNS zones"
default      = "nuon.run"
display_name = "Domain"
group        = "dns"

[[input]]
name         = "sub_domain"
description  = "Subdomain for the application"
default      = "whoami"
display_name = "Subdomain"
group        = "dns"