name          = "tailscale_oauth_client_secret"
display_name  = "Tailscale Oauth Client Secret"
description   = "Client Secret for the Oauth Trust Credentials for this cluster."

kubernetes_sync             = true
kubernetes_secret_namespace = "tailscale"
kubernetes_secret_name      = "tailscale-oauth-client-secret"
