# sandbox
terraform_version = "1.13.5"

[public_repo] # https://github.com/nuonco/aws-empty-sandbox/
repo      = "nuonco/aws-min-sandbox"
branch    = "main"
directory = "."

[vars]
enable_nuon_dns      = "true"
public_root_domain   = "{{ .nuon.install.id }}.{{.nuon.inputs.inputs.domain}}"
internal_root_domain = "internal.{{ .nuon.install.id }}.{{.nuon.inputs.inputs.domain}}"

[[var_file]]
contents = "./sandbox.tfvars"
