#:schema https://api.nuon.co/v1/general/config-schema?source=inputs
[[group]]
name         = "whoami"
description  = "configuration for whoami service"
display_name = "Whoami Config"

[[input]]
name         = "name"
description  = "--name flag for whoami"
default      = "whoami"
display_name = "name"
group        = "whoami"

[[input]]
name         = "subdomain"
description  = "Subdomain where whoami service will be served."
default      = "whoami"
display_name = "Subdomain"
group        = "whoami"
