terraform_version = "1.13.5"

[public_repo]
directory = "."
repo      = "nuonco/aws-eks-auto-sandbox"
branch    = "main"

[vars]
cluster_version = "1.34"
cluster_name    = "w-{{.nuon.install.id}}"
region          = "{{.nuon.install_stack.outputs.region}}"
vpc_id          = "{{.nuon.install_stack.outputs.vpc_id}}"

enable_ebs_csi  = "false"

enable_nuon_dns      = "true"
public_root_domain   = "{{.nuon.install.id}}.nuon.run"
internal_root_domain = "{{.nuon.install.id}}.internal.nuon.run"

[[var_file]]
contents = "./sandbox.tfvars"
