# helm

name           = "coder"
type           = "helm_chart"
chart_name     = "coder"
namespace      = "coder"
storage_driver = "configmap"
dependencies   = ["rds_cluster_coder"]

[helm_repo]
repo_url = "https://helm.coder.com/v2"
chart    = "coder"

[[values_file]]
contents = "./values/coder.yaml"
