terraform_version = "1.13.5"

[public_repo]
directory = "."
repo      = "nuonco/aws-eks-karpenter-sandbox"
branch    = "main"

[vars]
cluster_version = "1.33"
cluster_name    = "dd-{{.nuon.install.id}}"

enable_nuon_dns      = "true"
public_root_domain   = "{{.nuon.install.id}}.nuon.run"
internal_root_domain = "{{.nuon.install.id}}.internal.nuon.run"

[[var_file]]
contents = "./sandbox.tfvars"
