# action
name    = "kubectl_events"
timeout = "2m30s"

[[triggers]]
type = "manual"

[[steps]]
name            = "kubectl_events"
inline_contents = "./src/kubectl-events.sh"

[steps.env_vars]
NAMESPACE = "kube-system"
