#:schema https://api.nuon.co/v1/general/config-schema?type=helm
name           = "baserow"
type           = "helm_chart"
chart_name     = "baserow"
namespace      = "baserow"
storage_driver = "configmap"
dependencies   = ["default_storage_class", "baserow_s3_bucket"]

[helm_repo]
repo_url = "https://baserow.gitlab.io/baserow-chart"
chart    = "baserow"

[[values_file]]
contents = "./values/baserow/values.yaml"
