terraform_version = "1.11.3"

[public_repo]
directory = "."
repo      = "nuonco/terraform-azure-aks-sandbox"
branch    = "main"

[vars]
location             = "{{ .nuon.install.cloud_account.region }}"
resource_group_name  = "n-{{.nuon.install.id}}-rg"
cluster_name         = "n-{{.nuon.install.id}}"
vnet_name            = "n-{{.nuon.install.id}}-vnet"
subnet_name_private  = "n-{{.nuon.install.id}}-subnet-private"
subnet_name_public   = "n-{{.nuon.install.id}}-subnet-public"
enable_nuon_dns      = "true"
public_root_domain   = "{{ .nuon.install.id }}.{{.nuon.inputs.inputs.domain}}"
internal_root_domain = "internal.{{ .nuon.install.id }}.{{.nuon.inputs.inputs.domain}}"

[[var_file]]
contents = "./sandbox.tfvars"
