#:schema https://api.nuon.co/v1/general/config-schema?source=action
name    = "ingress_healthcheck"
timeout = "30s"

[[triggers]]
type = "manual"

[[steps]]
name    = "ingress-healthcheck"
command = "./healthcheck.sh"

[steps.public_repo]
repo      = "nuonco/example-app-configs"
directory = "aks-simple/src/actions/ingress"
branch    = "main"

[steps.env_vars]
INGRESS_NAME      = "{{.nuon.install.id}}-public"
INGRESS_NAMESPACE = "whoami"