#:schema https://api.nuon.co/v1/general/config-schema?type=helm

name         = "ingress"
type         = "helm_chart"
chart_name   = "ingress"
dependencies = ["whoami"]

[public_repo]
repo      = "nuonco/example-app-configs"
directory = "aks-simple/src/components/ingress"
branch    = "main"

[values]
domain           = "{{.nuon.inputs.inputs.sub_domain}}.{{.nuon.install.sandbox.outputs.nuon_dns.public_domain.name}}"
https_port       = "443"
service_name     = "whoami"
service_port     = "85"
install_name     = "{{.nuon.install.id}}"
namespace        = "whoami"
healthcheck_path = "/health"
