type        = "aws-cloudformation"
name        = "nuon-n8n-{{.nuon.install.id}}"
description = "QuickLink to install runner for n8n Workflow Automation Platform: Install {{.nuon.install.id}}"

# nested stack
vpc_nested_template_url    = "https://nuon-artifacts.s3.us-west-2.amazonaws.com/aws-cloudformation-templates/v0.1.6/vpc/eks/default/stack.yaml"
runner_nested_template_url = "https://nuon-artifacts.s3.us-west-2.amazonaws.com/aws-cloudformation-templates/v0.1.6/runner/asg/stack.yaml"

