# kubernetes-manifest
name         = "openhands_rbac"
type         = "kubernetes_manifest"
namespace    = "openhands"
manifest     = "./manifests/openhands-rbac.yaml"
dependencies = ["karpenter_nodepools"]
