#:schema https://api.nuon.co/v1/general/config-schema?type=helm
name           = "n8n_workers"
type           = "helm_chart"
chart_name     = "n8n-workers"
namespace      = "n8n"
storage_driver = "configmap"
dependencies   = ["n8n_main", "ollama_server"]
timeout        = "10m"

[public_repo]
repo      = "nuonco/example-app-configs"
directory = "n8n/src/helm/n8n-workers"
branch    = "main"

[[values_file]]
contents = "./values/n8n/n8n-workers.yaml"

