#:schema https://api.nuon.co/v1/general/config-schema?type=helm
name           = "ollama_server"
type           = "helm_chart"
chart_name     = "ollama"
namespace      = "n8n"
storage_driver = "configmap"
dependencies   = []
timeout        = "15m"

[public_repo]
repo      = "nuonco/example-app-configs"
directory = "n8n/src/helm/ollama"
branch    = "main"

[[values_file]]
contents = "./values/ollama/ollama.yaml"

