# helm
name           = "exampledb_postgres"
type           = "helm_chart"
dependencies   = ["grafana_postgres"]
chart_name     = "postgresql"
namespace      = "exampledb"
storage_driver = "configmap"


[public_repo]
repo      = "nuonco/example-app-configs"
directory = "grafana/src/helm/postgresql"
branch    = "main"

[[values_file]]
contents = "./values/exampledb-postgres/values.yaml"