#:schema https://api.nuon.co/v1/general/config-schema?type=terraform
name              = "rds_cluster_grafana"
type              = "terraform_module"
terraform_version = "1.11.3"

drift_schedule = "0 0 * * *"

[public_repo]
repo      = "nuonco/example-app-configs"
directory = "grafana/src/components/rds_cluster"
branch    = "main"

[vars]
identifier      = "grafana-{{ .nuon.install.id }}"
port            = "5432"
db_name         = "grafana"
db_user         = "grafana"
instance_class  = "{{ .nuon.install.inputs.grafana_db_instance_type }}"
subnet_group_id = "{{ .nuon.components.rds_subnet.outputs.id }}"

region     = "{{ .nuon.install_stack.outputs.region }}"
vpc_id     = "{{ .nuon.install_stack.outputs.vpc_id }}"
subnet_ids = "{{ index .nuon.sandbox.outputs.vpc.private_subnet_ids 0}},{{ index .nuon.sandbox.outputs.vpc.private_subnet_ids 1 }},{{ index .nuon.sandbox.outputs.vpc.private_subnet_ids 2 }}"

nuon_id = "{{ .nuon.install.id }}"

iam_database_authentication_enabled = "true"
deletion_protection                 = "false"
skip_final_snapshot                 = "true"
storage_encrypted                   = "true"

allocated_storage = "20"
apply_immediately = "true"
