# kubernetes-manifest

name         = "grafana_secrets"
type         = "kubernetes_manifest"
dependencies = ["rds_cluster_grafana"]

namespace = "grafana"
manifest  = """
# Secret for Grafana's internal database connection
# Note: The actual credentials are created by the grafana_rds_creds action
# This manifest creates the namespace and a placeholder that gets overwritten
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
"""
