# helm
name           = "grafana"
type           = "helm_chart"
chart_name     = "grafana"
namespace      = "grafana"
storage_driver = "configmap"
dependencies   = ["prometheus", "grafana_secrets", "exampledb_secrets", "rds_cluster_grafana", "rds_cluster_exampledb"]

[helm_repo]
repo_url = "https://grafana.github.io/helm-charts"
chart    = "grafana"

[[values_file]]
contents = "./values/grafana/values.yaml"
