type = "deprovision"
name = "{{.nuon.install.id}}-deprovision"
description = "Destroy all sandbox infrastructure"
display_name = "Deprovision Role"
permissions_boundary = "./deprovision_boundary.json"

[[policies]]
name = "{{.nuon.install.id}}-deprovision-route53"
contents = """
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Route53ZoneDeletion",
      "Effect": "Allow",
      "Action": [
        "route53:DeleteHostedZone",
        "route53:GetHostedZone",
        "route53:ListResourceRecordSets",
        "route53:ChangeResourceRecordSets"
      ],
      "Resource": "*"
    }
  ]
}
"""

[[policies]]
name = "{{.nuon.install.id}}-deprovision-iam"
contents = """
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "IAMRoleDeletion",
      "Effect": "Allow",
      "Action": [
        "iam:DeleteRole",
        "iam:DeleteRolePolicy",
        "iam:DetachRolePolicy",
        "iam:DeletePolicy",
        "iam:ListRolePolicies",
        "iam:ListAttachedRolePolicies",
        "iam:GetRole"
      ],
      "Resource": [
        "arn:aws:iam::*:role/*{{.nuon.install.id}}*",
        "arn:aws:iam::*:policy/*{{.nuon.install.id}}*"
      ]
    }
  ]
}
"""

[[policies]]
name = "{{.nuon.install.id}}-deprovision-vpc"
contents = """
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "VPCNetworkDeletion",
      "Effect": "Allow",
      "Action": [
        "ec2:DeleteSecurityGroup",
        "ec2:DeleteSubnet",
        "ec2:DeleteVpc",
        "ec2:DeleteNatGateway",
        "ec2:DeleteInternetGateway",
        "ec2:DetachInternetGateway",
        "ec2:DeleteRouteTable",
        "ec2:DisassociateRouteTable",
        "ec2:DeleteRoute",
        "ec2:ReleaseAddress",
        "ec2:DescribeVpcs",
        "ec2:DescribeSubnets",
        "ec2:DescribeSecurityGroups",
        "ec2:DescribeNatGateways",
        "ec2:DescribeInternetGateways",
        "ec2:DescribeRouteTables",
        "ec2:DescribeAddresses",
        "ec2:RevokeSecurityGroupIngress",
        "ec2:RevokeSecurityGroupEgress"
      ],
      "Resource": "*"
    }
  ]
}
"""

[[policies]]
name = "{{.nuon.install.id}}-deprovision-compute"
contents = """
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "EC2InstanceDeletion",
      "Effect": "Allow",
      "Action": [
        "autoscaling:DeleteAutoScalingGroup",
        "autoscaling:DeleteLaunchConfiguration",
        "autoscaling:DescribeAutoScalingGroups",
        "autoscaling:UpdateAutoScalingGroup",
        "ec2:TerminateInstances",
        "ec2:DescribeInstances"
      ],
      "Resource": "*"
    }
  ]
}
"""

[[policies]]
name = "{{.nuon.install.id}}-deprovision-cfn"
contents = """
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "CloudFormationStackDeletion",
      "Effect": "Allow",
      "Action": [
        "cloudformation:DeleteStack",
        "cloudformation:DescribeStacks",
        "cloudformation:DescribeStackResource",
        "cloudformation:DescribeStackResources"
      ],
      "Resource": "*"
    }
  ]
}
"""

[[policies]]
name = "{{.nuon.install.id}}-deprovision-ecr"
contents = """
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "ECRRepositoryDeletion",
      "Effect": "Allow",
      "Action": [
        "ecr:DeleteRepository",
        "ecr:DescribeRepositories"
      ],
      "Resource": "*"
    }
  ]
}
"""
