type = "provision"
name = "{{.nuon.install.id}}-provision"
description = "provision"
display_name = "provision"
permissions_boundary = "./provision_boundary.json"

[[policies]]
managed_policy_name = "AdministratorAccess"
