# action
name    = "default_storage_class"
timeout = "1m"

[[triggers]]
type           = "pre-deploy-component"
component_name = "rds_subnet"

[[triggers]]
type = "manual"

[[steps]]
name    = "make_gp2_default_storage_class"
inline_contents = """
#!/usr/bin/env sh
kubectl auth whoami -o json | jq -c
kubectl patch storageclass gp2 -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
"""