type                 = "deprovision"
name                 = "{{.nuon.install.id}}-deprovision"
description          = "deprovision sandbox and components. delete the cf stack separately to remove the runner, ec2 vm, and vpc."
display_name         = "deprovision role"
permissions_boundary = "./deprovision_boundary.json"

[[policies]]
name = "{{.nuon.install.id}}-deprovision-policy-rds"
contents = "./maintenance_policy_rds.json"

[[policies]]
name = "{{.nuon.install.id}}-deprovision-policy-iam"
contents = "./maintenance_policy_iam.json"

[[policies]]
name = "{{.nuon.install.id}}-deprovision-policy-secrets"
contents = "./maintenance_policy_secrets.json"

[[policies]]
name = "{{.nuon.install.id}}-deprovision-policy-route53"
contents = "./maintenance_policy_route53.json"

[[policies]]
name = "{{.nuon.install.id}}-deprovision-policy-acm"
contents = "./maintenance_policy_acm.json"

[[policies]]
name = "{{.nuon.install.id}}-deprovision-policy-ecr"
contents = "./maintenance_policy_ecr.json"

[[policies]]
name = "{{.nuon.install.id}}-deprovision-policy-logs"
contents = "./maintenance_policy_logs.json"

[[policies]]
name = "{{.nuon.install.id}}-deprovision-policy-kms"
contents = "./maintenance_policy_kms.json"

[[policies]]
name = "{{.nuon.install.id}}-deprovision-policy-eks"
contents = "./maintenance_policy_eks.json"

[[policies]]
name = "{{.nuon.install.id}}-deprovision-policy-networking"
contents = "./maintenance_policy_networking.json"
