#:schema https://api.nuon.co/v1/general/config-schema?source=helm
name           = "karpenter_nodepools"
type           = "helm_chart"
chart_name     = "karpenter-nodepools"
storage_driver = "configmap"

[public_repo]
repo      = "nuonco/example-app-configs"
directory = "clickhouse/src/components/karpenter-nodepools"
branch    = "main"

[[values_file]]
contents = "./values/karpenter-nodepools.yaml"
