#:schema https://api.nuon.co/v1/general/config-schema?source=kubernetes-manifest
name      = "clickhouse_service"
type      = "kubernetes_manifest"
namespace = "clickhouse"

dependencies = ["clickhouse_cluster"]
manifest = "./manifests/clickhouse_service.yaml"
