replicaCount: 2

image:
  repository: n8nio/n8n
  tag: latest
  pullPolicy: IfNotPresent

deployment:
  command:
    - n8n
    - worker
    - --concurrency=10

config:
  database:
    postgresdb:
      database: n8n
      user: n8n
      password: ""
  
  redis:
    host: redis-master
    port: "6379"
    password: ""
    db: "0"

secret:
  encryption_key: ""

extraEnv:
  EXECUTIONS_MODE: "queue"
  N8N_LOG_LEVEL: "info"

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "2000m"

