name          = "tailscale_oauth_client_id"
display_name  = "Tailscale Oauth Client ID"
description   = "Client ID for the Oauth Trust Credentials for this cluster."
default       = "dne"

kubernetes_sync             = true
kubernetes_secret_namespace = "tailscale"
kubernetes_secret_name      = "tailscale-oauth-client-id"
