name          = "cockroachdb_admin_pw"
display_name  = "CockroachDB Admin PW"
description   = "Password for the default cockroachdb admin user. This password is used to access the cluster admin."

kubernetes_sync             = true
kubernetes_secret_namespace = "cockroach"
kubernetes_secret_name      = "admin-pw"
