type                 = "maintenance"
name                 = "{{.nuon.install.id}}-maintenance"
description          = "maintenance role for ch-{{nuon.install.id}} install"
display_name         = "maintenance ch-{{nuon.install.id}}"
permissions_boundary = "./maintenance_boundary.json"

[[policies]]
managed_policy_name = "AdministratorAccess"
