type        = "aws-cloudformation"
name        = "nuon-demos-httpbin-{{.nuon.install.id}}"
description = "QuickLink to install runner for the HTTPBin app config: Install {{.nuon.install.id}}"

# nested stack
vpc_nested_template_url    = "https://nuon-artifacts.s3.us-west-2.amazonaws.com/aws-cloudformation-templates/v0.1.9/vpc/eks/default/stack.yaml"
runner_nested_template_url = "https://nuon-artifacts.s3.us-west-2.amazonaws.com/aws-cloudformation-templates/v0.1.9/runner/asg/stack.yaml"
