type                 = "provision"
name                 = "{{.nuon.install.id}}-provision"
description          = "provision role for ch-{{nuon.install.id}} install"
display_name         = "provision ch-{{nuon.install.id}}"
permissions_boundary = "./provision_boundary.json"

[[policies]]
managed_policy_name = "AdministratorAccess"
