#:schema https://api.nuon.co/v1/general/config-schema?type=action
name    = "temporal_ensure_namespaces"
timeout = "1m30s"

[[triggers]]
type           = "post-deploy-component"
component_name = "temporal"

[[triggers]]
type = "manual"

[[steps]]
name            = "ensure"
inline_contents = "./src/temporal/ensure-namespaces.sh"
