#:schema https://api.nuon.co/v1/general/config-schema?type=action
name    = "ts_tailnet"
timeout = "10s"

[[triggers]]
type           = "pre-deploy-component"
component_name = "temporal_ai_agent"

[[triggers]]
type = "manual"

[[steps]]
name    = "get"
inline_contents = "./src/tailscale/get-tailnet.sh"
