# action
name    = "alb"
timeout = "1m"

[[triggers]]
type = "manual"

[[steps]]
name = "elbv2"
inline_contents = "./src/alb/elbv2.sh"

[steps.env_vars]
INGRESS_NAME      = "{{.nuon.install.id}}-public"
INGRESS_NAMESPACE = "whoami"

[[steps]]
name = "upstreams"
inline_contents = "./src/alb/upstreams.sh"

[steps.env_vars]
INGRESS_NAME      = "{{.nuon.install.id}}-public"
INGRESS_NAMESPACE = "whoami"
