# helm
name           = "karpenter_nodepools"
type           = "helm_chart"
chart_name     = "karpenter-nodepools"
storage_driver = "configmap"

[public_repo]
repo      = "nuonco/example-app-configs"
directory = "data-ops/src/components/karpenter-nodepools"
branch    = "fd/new-demo/data-ops"

[[values_file]]
contents = "./values/karpenter-nodepools.yaml"
