#:schema https://api.nuon.co/v1/general/config-schema?source=helm
name      = "crd_tailscale_operator"
type      = "kubernetes_manifest"
namespace = "tailscale"

manifest = "./manifests/tailscale_operator.yaml"
