#:schema https://api.nuon.co/v1/general/config-schema?type=kubernetes-manifest
name      = "tailscale_proxy"
type      = "kubernetes_manifest"
namespace = "tailscale"

dependencies = ["crd_tailscale_operator"]

manifest = "./manifests/tailscale_proxy.yaml"
