#:schema https://api.nuon.co/v1/general/config-schema?source=kubernetes-manifest
name      = "clickhouse_ingress"
type      = "kubernetes_manifest"
namespace = "clickhouse"

dependencies = ["clickhouse_service", "tailscale_proxy"]
manifest = "./manifests/clickhouse_ingress.yaml"
