name          = "llm_key"
display_name  = "LLM_KEY"
description   = "Your API key for the selected provider."

kubernetes_sync             = true
kubernetes_secret_namespace = "temporal-ai-agent"
kubernetes_secret_name      = "llm-key"
