---
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    clusterName: "{{ .nuon.install.sandbox.outputs.cluster.name }}"
    site: "{{ .nuon.inputs.inputs.datadog_site }}"
    # NOTE(fd): this secret is copied in by the runner. it corresponds
    credentials:
      apiSecret:
        secretName: datadog-api-key
        keyName: value
  features:
    logCollection:
      enabled: true
      containerCollectAll: true
