---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # we use a unique name and host since we would like for these to be unique across installs
  name: 'temporal-web-{{ .nuon.install.id }}'
  namespace: temporal
  labels:
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: temporal
    app.kubernetes.io/name: temporal
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - 'temporal-web-{{ .nuon.install.id }}'
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: temporal-web
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # we use a unique name and host since we would like for these to be unique across installs
  name: 'temporal-frontend-{{ .nuon.install.id }}'
  namespace: temporal
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: temporal
    app.kubernetes.io/name: temporal
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - 'temporal-frontend-{{ .nuon.install.id }}'
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: temporal-frontend
                port:
                  name: http
