[[group]]
name         = "dns"
description  = "DNS Configurations"
display_name = "Configurations for the root domain for Route53"

[[input]]
name         = "domain"
description  = "domain for the AWS Lambda e.g., nuon.run or stage.nuon.run"
default      = "nuon.run"
display_name = "Domain"
group        = "dns"

[[input]]
name         = "sub_domain"
description  = "The sub domain for the AWS Lambda"
default      = "api"
display_name = "Sub Domain"
group        = "dns"
