type        = "aws-cloudformation"
name        = "nuon-demos-clickhouse-{{.nuon.install.id}}"
description = "QuickLink to install runner for Clickhouse Demo: Install {{.nuon.install.id}}"

# nested stack
vpc_nested_template_url    = "https://nuon-artifacts.s3.us-west-2.amazonaws.com/aws-cloudformation-templates/v0.2.1/vpc/eks/default/stack.yaml"
runner_nested_template_url = "https://nuon-artifacts.s3.us-west-2.amazonaws.com/aws-cloudformation-templates/v0.2.1/runner/asg/stack.yaml"
