# terraform
name              = "certificate"
type              = "terraform_module"
terraform_version = "1.11.3"
drift_schedule    = "*/45 * * * *"

[public_repo]
repo      = "nuonco/components"
directory = "aws/certificate-v2"
branch    = "main"

[vars]
install_id  = "{{ .nuon.install.id }}"
region      = "{{ .nuon.install_stack.outputs.region }}"
zone_id     = "{{ .nuon.sandbox.outputs.nuon_dns.public_domain.zone_id }}"
domain_name = "*.{{ .nuon.sandbox.outputs.nuon_dns.public_domain.name }}"
