# kubernetes-manifest
name      = "clickhouse_service"
type      = "kubernetes_manifest"
namespace = "clickhouse"

dependencies = ["clickhouse_cluster", "certificate"]
manifest = "./manifests/clickhouse_service.yaml"
