# kubernetes-manifest
name      = "clickhouse_ingress"
type      = "kubernetes_manifest"
namespace = "clickhouse"

dependencies = ["clickhouse_service"]
manifest = "./manifests/clickhouse_ingress.yaml"
