# kubernetes-manifest

name = "twenty_service_redis"
type = "kubernetes_manifest"
dependencies = ["twenty_deployment_redis"]

namespace = "twentycrm"
manifest = """
apiVersion: v1
kind: Service
metadata:
  name: twentycrm-redis
  namespace: twentycrm
spec:
  internalTrafficPolicy: Cluster
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: twentycrm-redis
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
"""