# kubernetes-manifest

name = "twenty_pv_docker_data"
type = "kubernetes_manifest"
dependencies = []

namespace = "twentycrm"
manifest = """
apiVersion: v1
kind: PersistentVolume
metadata:
  name: twentycrm-docker-data-pv
  namespace: twentycrm
spec:
  storageClassName: default
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/data/twentycrm/docker-data
  persistentVolumeReclaimPolicy: Retain
"""