# kubernetes-manifest

name = "twenty_secret"
type = "kubernetes_manifest"
dependencies = []

namespace = "twentycrm"
manifest = """
apiVersion: v1
kind: Secret
metadata:
  name: tokens
  namespace: twentycrm
type: Opaque
stringData:
  accessToken: "{{ .nuon.inputs.inputs.access_token_secret }}"
  loginToken: "{{ .nuon.inputs.inputs.login_token_secret }}"
  refreshToken: "{{ .nuon.inputs.inputs.refresh_token_secret }}"
  fileToken: "{{ .nuon.inputs.inputs.file_token_secret }}"
  appSecret: "{{ .nuon.inputs.inputs.app_secret }}"
"""