name          = "datadog_api_key"
display_name  = "DataDog API Key"
description   = "API Key for use by the datadog agent.."

kubernetes_sync             = true
kubernetes_secret_namespace = "datadog"
kubernetes_secret_name      = "datadog-api-key"
