name          = "datadog_app_key"
display_name  = "DataDog App Key"
description   = "App Key for use by the datadog agent.."

kubernetes_sync             = true
kubernetes_secret_namespace = "datadog"
kubernetes_secret_name      = "datadog-app-key"
