type                 = "deprovision"
name                 = "{{.nuon.install.id}}-deprovision"
description          = "{{ .nuon.install.id }} deprovision role for BYO-LLM Open WebUI install"
display_name         = "{{ .nuon.install.id }}-deprovision"
permissions_boundary = "./deprovision_boundary.json"

[[policies]]
managed_policy_name = "AdministratorAccess"
