#:schema https://api.nuon.co/v1/general/config-schema?source=action

name    = "ecs_service_linked_role"
timeout = "1m"

[[triggers]]
type           = "pre-component-deploy"
component_name = "cluster"

[[steps]]
name            = "ensure"
inline_contents = "./src/ensure-service-linked-role.sh"
