# inputs

[[group]]
name         = "coder"
description  = "Coder Configrations for the Coder Cloud Development Environment platform https://github.com/coder/coder/releases"
display_name = "Coder Configurations"

[[input]]
name         = "release"
description  = "The release of Coder to deploy."
default      = "v2.28.6"
display_name = "Release"
internal     = true 
group        = "coder"

[[input]]
name         = "replicas"
description  = "The number of replicas of the Coder control plane pods to deploy"
default      = "1"
display_name = "Coder Replicas"
internal     = true 
group        = "coder"

[[input]]
name         = "provisioners"
description  = "The number of Terraform provisioners to create and destroy workspace resources"
default      = "3"
display_name = "Terraform Provisioners"
internal     = true 
group        = "coder"

[[input]]
name         = "telemetry"
description  = "Enable telemetry collection"
default      = "true"
display_name = "Telemetry"
internal     = false
user_configurable = true 
group        = "coder"

[[input]]
name         = "max_token_lifetime"
description  = "Maximum lifetime of a user token for CLI and API access"
default      = "8760h0m0s"
display_name = "Token Lifetime"
internal     = false
user_configurable = true 
group        = "coder"

[[input]]
name         = "session_duration"
description  = "Duration of a user session before requireing re-authentication"
default      = "168h0m0s"
display_name = "Session duration"
internal     = false
user_configurable = true 
group        = "coder"

[[input]]
name         = "block_direct"
description  = "Block peer-to-peer (aka direct) workspace connections. All workspace connections from the CLI will be proxied through Coder"
default      = "false"
display_name = "Block Direct Connections"
internal     = false
user_configurable = true 
group        = "coder"

[[group]]
name         = "infrastructure"
description  = "EKS https://docs.aws.amazon.com/eks/"
display_name = "Infrastructure"

[[input]]
name         = "cluster_version"
description  = "Kubernetes version for the EKS cluster"
default      = "1.34"
display_name = "Kubernetes Version"
required     = true
internal     = true
group        = "infrastructure"


[[group]]
name         = "database"
description  = "RDS PostgreSQL database configuration - See https://aws.amazon.com/rds/instance-types/"
display_name = "Database Configuration"

[[input]]
name         = "coder_db_instance_type"
description  = "RDS instance type for Coder database."
default      = "db.t4g.micro"
display_name = "Database Instance Type"
required     = true
internal     = true
group        = "database"
