# inputs
[[group]]
name         = "dns"
description  = "DNS Configrations"
display_name = "Configurations for the root domain for Route53"

[[input]]
name         = "domain"
description  = "domain for the AWS API Gateway e.g., nuon.run or stage.nuon.run"
default      = "nuon.run"
display_name = "Domain"
group        = "dns"

[[input]]
name         = "sub_domain"
description  = "The sub domain for the AWS API Gateway"
default      = "api"
display_name = "Sub Domain"
group        = "dns"

[[group]]
name         = "eks"
description  = "EKS Configrations"
display_name = "Configurations for the EKS Cluster"

[[input]]
name         = "cluster_name"
display_name = "Cluster Name"
description  = "The name of the EKS Cluster"
required     = true
default      = ""
group        = "eks"

[[input]]
name         = "namespaces"
display_name = "Namespaces"
description  = "The namespaces to create and grant the runner access to."
default      = "sourdough,persimmon,tartar"
required     = true
group        = "eks"
