# action

name    = "default_storage_class"
timeout = "1m"

[[triggers]]
type = "manual"

[[steps]]
name    = "make_ebs-auto_default_storage_class"
inline_contents = """
#!/usr/bin/env sh
kubectl auth whoami -o json | jq -c
kubectl patch storageclass ebs-auto -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
"""
