name    = "grafana_password"
timeout = "1m"

[[triggers]]
type = "manual"

[[steps]]
name    = "Retrieve Grafana Admin Password"
command = "./get-password.sh"

[steps.public_repo]
repo      = "nuonco/example-app-configs"
directory = "coder/src/actions/grafana-password"
branch    = "mm/coder-observe-kubelogstream"

[steps.env_vars]
REGION     = "{{ .nuon.install_stack.outputs.region }}"
INSTALL_ID = "{{ .nuon.install.id }}"
